package com.jobbud.ws.enums;

public enum GeneralStatus {
    ACCEPTED, DECLINED, FINISHED, OFFERED, REJECTED, REQUESTED_FINISH, REQUESTED_APPROVE, WAITING_OFFERS,
    WAITING_FINISH,
    WAITING_APPROVE,
}
